---
inherit_mode:
  merge:
    - Exclude
    - IgnoredMethods

Bundler/GemVersion:
  Enabled: true
  EnforcedStyle: forbidden

Gemspec/DependencyVersion:
  Enabled: true
  EnforcedStyle: required

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/HeredocArgumentClosingParenthesis:
  Enabled: true

Layout/RedundantLineBreak:
  Enabled: true

Layout/SingleLineBlockChain:
  Enabled: true
